apiVersion: apps/v1
kind: Deployment
metadata: { name: jaeger-collector }
spec:
  replicas: 1
  selector: { matchLabels: { app: jaeger-collector } }
  template:
    metadata: { labels: { app: jaeger-collector } }
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.67.0
          env: [{ name: COLLECTOR_OTLP_ENABLED, value: "true" }]
          ports:
            - { name: otlp, containerPort: 4317 }
            - { name: query, containerPort: 16686 }
---
apiVersion: v1
kind: Service
metadata: { name: jaeger-collector }
spec:
  selector: { app: jaeger-collector }
  ports:
    - { name: otlp, port: 4317, targetPort: otlp }
    - { name: query, port: 16686, targetPort: query }
