CREATE DATABASE IF NOT EXISTS rag_cdc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'canal'@'%' IDENTIFIED BY 'canal-local-only';
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'canal'@'%';

CREATE USER IF NOT EXISTS 'rag_cdc'@'%' IDENTIFIED BY 'rag-cdc-local-only';
GRANT SELECT, INSERT, UPDATE, DELETE ON rag_cdc.* TO 'rag_cdc'@'%';

USE rag_cdc;
CREATE TABLE IF NOT EXISTS document_records (
  id VARCHAR(128) NOT NULL,
  source VARCHAR(512) NOT NULL,
  file_path VARCHAR(2048) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_document_records_source (source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

FLUSH PRIVILEGES;
