// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: rag.proto

package ragpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	SessionId     int64                  `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *ChatRequest) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Answer             string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	AgentTrace         []string               `protobuf:"bytes,2,rep,name=agent_trace,json=agentTrace,proto3" json:"agent_trace,omitempty"`
	TriggerWebFallback bool                   `protobuf:"varint,3,opt,name=trigger_web_fallback,json=triggerWebFallback,proto3" json:"trigger_web_fallback,omitempty"`
	Sources            []*Source              `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	ReasoningSummary   []string               `protobuf:"bytes,5,rep,name=reasoning_summary,json=reasoningSummary,proto3" json:"reasoning_summary,omitempty"`
	Cached             bool                   `protobuf:"varint,6,opt,name=cached,proto3" json:"cached,omitempty"`
	DurationMs         int64                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *ChatResponse) GetAgentTrace() []string {
	if x != nil {
		return x.AgentTrace
	}
	return nil
}

func (x *ChatResponse) GetTriggerWebFallback() bool {
	if x != nil {
		return x.TriggerWebFallback
	}
	return false
}

func (x *ChatResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ChatResponse) GetReasoningSummary() []string {
	if x != nil {
		return x.ReasoningSummary
	}
	return nil
}

func (x *ChatResponse) GetCached() bool {
	if x != nil {
		return x.Cached
	}
	return false
}

func (x *ChatResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *SearchHit) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SearchHit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SearchHit) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{5}
}

func (x *Source) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Source) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Source) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Source) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Source) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Source) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type IndexDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	FilePath      string                 `protobuf:"bytes,4,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentRequest) Reset() {
	*x = IndexDocumentRequest{}
	mi := &file_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentRequest) ProtoMessage() {}

func (x *IndexDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentRequest.ProtoReflect.Descriptor instead.
func (*IndexDocumentRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{6}
}

func (x *IndexDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *IndexDocumentRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *IndexDocumentRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IndexDocumentRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type IndexDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Chunks        int32                  `protobuf:"varint,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexDocumentResponse) Reset() {
	*x = IndexDocumentResponse{}
	mi := &file_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexDocumentResponse) ProtoMessage() {}

func (x *IndexDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexDocumentResponse.ProtoReflect.Descriptor instead.
func (*IndexDocumentResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{7}
}

func (x *IndexDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IndexDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IndexDocumentResponse) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	VectorStore   string                 `protobuf:"bytes,2,opt,name=vector_store,json=vectorStore,proto3" json:"vector_store,omitempty"`
	Chunks        int64                  `protobuf:"varint,3,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVectorStore() string {
	if x != nil {
		return x.VectorStore
	}
	return ""
}

func (x *HealthResponse) GetChunks() int64 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\vcrag.rag.v1\"a\n" +
	"\vChatRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03R\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x8e\x02\n" +
	"\fChatResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1f\n" +
	"\vagent_trace\x18\x02 \x03(\tR\n" +
	"agentTrace\x120\n" +
	"\x14trigger_web_fallback\x18\x03 \x01(\bR\x12triggerWebFallback\x12-\n" +
	"\asources\x18\x04 \x03(\v2\x13.crag.rag.v1.SourceR\asources\x12+\n" +
	"\x11reasoning_summary\x18\x05 \x03(\tR\x10reasoningSummary\x12\x16\n" +
	"\x06cached\x18\x06 \x01(\bR\x06cached\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x03R\n" +
	"durationMs\":\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"<\n" +
	"\x0eSearchResponse\x12*\n" +
	"\x04hits\x18\x01 \x03(\v2\x16.crag.rag.v1.SearchHitR\x04hits\"g\n" +
	"\tSearchHit\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"\x86\x01\n" +
	"\x06Source\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\"\x8a\x01\n" +
	"\x14IndexDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1b\n" +
	"\tfile_path\x18\x04 \x01(\tR\bfilePath\"c\n" +
	"\x15IndexDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06chunks\x18\x03 \x01(\x05R\x06chunks\"\x0f\n" +
	"\rHealthRequest\"c\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12!\n" +
	"\fvector_store\x18\x02 \x01(\tR\vvectorStore\x12\x16\n" +
	"\x06chunks\x18\x03 \x01(\x03R\x06chunks2\xa7\x02\n" +
	"\n" +
	"RagService\x12;\n" +
	"\x04Chat\x12\x18.crag.rag.v1.ChatRequest\x1a\x19.crag.rag.v1.ChatResponse\x12A\n" +
	"\x06Search\x12\x1a.crag.rag.v1.SearchRequest\x1a\x1b.crag.rag.v1.SearchResponse\x12V\n" +
	"\rIndexDocument\x12!.crag.rag.v1.IndexDocumentRequest\x1a\".crag.rag.v1.IndexDocumentResponse\x12A\n" +
	"\x06Health\x12\x1a.crag.rag.v1.HealthRequest\x1a\x1b.crag.rag.v1.HealthResponseB=Z;github.com/example/crag-expert-system/api/proto/ragpb;ragpbb\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rag_proto_goTypes = []any{
	(*ChatRequest)(nil),           // 0: crag.rag.v1.ChatRequest
	(*ChatResponse)(nil),          // 1: crag.rag.v1.ChatResponse
	(*SearchRequest)(nil),         // 2: crag.rag.v1.SearchRequest
	(*SearchResponse)(nil),        // 3: crag.rag.v1.SearchResponse
	(*SearchHit)(nil),             // 4: crag.rag.v1.SearchHit
	(*Source)(nil),                // 5: crag.rag.v1.Source
	(*IndexDocumentRequest)(nil),  // 6: crag.rag.v1.IndexDocumentRequest
	(*IndexDocumentResponse)(nil), // 7: crag.rag.v1.IndexDocumentResponse
	(*HealthRequest)(nil),         // 8: crag.rag.v1.HealthRequest
	(*HealthResponse)(nil),        // 9: crag.rag.v1.HealthResponse
}
var file_rag_proto_depIdxs = []int32{
	5, // 0: crag.rag.v1.ChatResponse.sources:type_name -> crag.rag.v1.Source
	4, // 1: crag.rag.v1.SearchResponse.hits:type_name -> crag.rag.v1.SearchHit
	0, // 2: crag.rag.v1.RagService.Chat:input_type -> crag.rag.v1.ChatRequest
	2, // 3: crag.rag.v1.RagService.Search:input_type -> crag.rag.v1.SearchRequest
	6, // 4: crag.rag.v1.RagService.IndexDocument:input_type -> crag.rag.v1.IndexDocumentRequest
	8, // 5: crag.rag.v1.RagService.Health:input_type -> crag.rag.v1.HealthRequest
	1, // 6: crag.rag.v1.RagService.Chat:output_type -> crag.rag.v1.ChatResponse
	3, // 7: crag.rag.v1.RagService.Search:output_type -> crag.rag.v1.SearchResponse
	7, // 8: crag.rag.v1.RagService.IndexDocument:output_type -> crag.rag.v1.IndexDocumentResponse
	9, // 9: crag.rag.v1.RagService.Health:output_type -> crag.rag.v1.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
